"""initial schema

Revision ID: ed9f6d7e5375
Revises: 
Create Date: 2026-09-24 17:16:04.625157

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'ed9f6d7e5375'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_channel_code')
    )
    op.create_index(op.f('ix_channel_code'), 'channel', ['code'], unique=False)
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_base', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_base', name='uq_product_sku_base')
    )
    op.create_index(op.f('ix_product_sku_base'), 'product', ['sku_base'], unique=False)
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('ean', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_variant_sku')
    )
    op.create_index(op.f('ix_variant_ean'), 'variant', ['ean'], unique=False)
    op.create_index(op.f('ix_variant_product_id'), 'variant', ['product_id'], unique=False)
    op.create_index(op.f('ix_variant_sku'), 'variant', ['sku'], unique=False)
    op.create_table('conflict_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('old_qty', sa.Integer(), nullable=False),
    sa.Column('new_qty', sa.Integer(), nullable=False),
    sa.Column('loser_qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_log_channel_id'), 'conflict_log', ['channel_id'], unique=False)
    op.create_index(op.f('ix_conflict_log_variant_id'), 'conflict_log', ['variant_id'], unique=False)
    op.create_table('inventory_level',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ),
    sa.PrimaryKeyConstraint('variant_id', 'channel_id'),
    sa.UniqueConstraint('variant_id', 'channel_id', name='uq_inventory_variant_channel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_level')
    op.drop_index(op.f('ix_conflict_log_variant_id'), table_name='conflict_log')
    op.drop_index(op.f('ix_conflict_log_channel_id'), table_name='conflict_log')
    op.drop_table('conflict_log')
    op.drop_index(op.f('ix_variant_sku'), table_name='variant')
    op.drop_index(op.f('ix_variant_product_id'), table_name='variant')
    op.drop_index(op.f('ix_variant_ean'), table_name='variant')
    op.drop_table('variant')
    op.drop_index(op.f('ix_product_sku_base'), table_name='product')
    op.drop_table('product')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_channel_code'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
